export const LOGIN_STARTED = "LOGIN_STARTED";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const LOGOUT_STARTED = "LOGOUT_STARTED";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAIL = "LOGOUT_FAIL";

export const GET_ALL_STARTED = "GET_ALL_STARTED";
export const GET_ALL_SUCCESS = "GET_ALL_SUCCESS";
export const GET_ALL_FAIL = "GET_ALL_FAIL";

export const GET_USERS_STARTED = "GET_USERS_STARTED";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const GET_USERS_FAIL = "GET_USERS_FAIL";

export const GET_QUESTIONS_STARTED = "GET_QUESTIONS_STARTED";
export const GET_QUESTIONS_SUCCESS = "GET_QUESTIONS_SUCCESS";
export const GET_QUESTIONS_FAIL = "GET_QUESTIONS_FAIL";

export const GET_ANSWERS_STARTED = "GET_ANSWERS_STARTED";
export const GET_ANSWERS_SUCCESS = "GET_ANSWERS_SUCCESS";
export const GET_ANSWERS_FAIL = "GET_ANSWERS_FAIL";

export const CREATE_QUESTION_STARTED = "CREATE_QUESTION_STARTED";
export const CREATE_QUESTION_SUCCESS = "CREATE_QUESTION_SUCCESS";
export const CREATE_QUESTION_FAIL = "CREATE_QUESTION_FAIL";

export const ADD_ANSWER_STARTED = "ADD_ANSWER_STARTED";
export const ADD_ANSWER_SUCCESS = "ADD_ANSWER_SUCCESS";
export const ADD_ANSWER_FAIL = "ADD_ANSWER_FAIL";

export const UPDATE_QUESTION_STARTED = "UPDATE_QUESTION_STARTED";
export const UPDATE_QUESTION_SUCCESS = "UPDATE_QUESTION_SUCCESS";
export const UPDATE_QUESTION_FAIL = "UPDATE_QUESTION_FAIL";

export const DELETE_QUESTION_STARTED = "DELETE_QUESTION_STARTED";
export const DELETE_QUESTION_SUCCESS = "DELETE_QUESTION_SUCCESS";
export const DELETE_QUESTION_FAIL = "DELETE_QUESTION_FAIL";

export const ADD_TWEET_STARTED = "ADD_TWEET_STARTED";
export const ADD_TWEET_SUCCESS = "ADD_TWEET_SUCCESS";
export const ADD_TWEET_FAIL = "ADD_TWEET_FAIL";
