export const LOGIN_STARTED = 'LOGIN_STARTED';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const LOGOUT_STARTED = 'LOGOUT_STARTED';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAIL = 'LOGOUT_FAIL';

export const ADD_TWEET_STARTED = 'ADD_TWEET_STARTED';
export const ADD_TWEET_SUCCESS = 'ADD_TWEET_SUCCESS';
export const ADD_TWEET_FAIL = 'ADD_TWEET_FAIL';
